# Generated by Django 5.2.11 on 2026-02-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll_number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('department', models.CharField(default='Computer Science', max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('face_encoding', models.BinaryField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='student_photos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['roll_number'],
            },
        ),
    ]
