# Generated by Django 5.2.11 on 2026-02-15 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('entry_time', models.TimeField(blank=True, null=True)),
                ('exit_time', models.TimeField(blank=True, null=True)),
                ('is_late', models.BooleanField(default=False)),
                ('is_early_exit', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], default='ENTRY', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='accounts.student')),
            ],
            options={
                'ordering': ['-date', '-entry_time'],
                'unique_together': {('student', 'date')},
            },
        ),
    ]
