# Generated by Django 5.2.11 on 2026-02-15 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Holiday name (e.g., Republic Day)', max_length=100)),
                ('date', models.DateField(help_text='Date of the holiday', unique=True)),
                ('description', models.TextField(blank=True, help_text='Additional details about the holiday', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this holiday is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
